# Generated by Django 2.2.1 on 2019-07-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('number', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('course_quality', models.TextField(null=True)),
                ('difficulty', models.TextField(null=True)),
            ],
        ),
    ]
