# Generated by Django 2.1.7 on 2019-08-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_submitteddescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitteddescription',
            name='course',
            field=models.ManyToManyField(to='recommender.Course'),
        ),
    ]
