# Generated by Django 2.1.7 on 2019-08-03 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommender', '0003_submitteddescription_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('course', models.ManyToManyField(blank=True, null=True, to='recommender.Course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='submitteddescription',
            name='course',
        ),
        migrations.AlterField(
            model_name='submitteddescription',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
